EtlConfig:
  RetryAttempts: 3
  RetryDelay: "00:00:30"
  HealthCheckInterval: "00:01:00"
  ServiceStatusFile: "service-status.json"

Serilog:
  Using:
    - Serilog.Sinks.Console
    - Serilog.Sinks.File
  MinimumLevel:
    Default: Information
    Override:
      Microsoft: Warning
      System: Warning
      Microsoft.AspNetCore: Warning
  Enrich:
    - FromLogContext
    - WithMachineName
    - WithThreadId
  WriteTo:
    - Name: Console
      Args:
        outputTemplate: "[{Timestamp:HH:mm:ss.fff} {Level:u3}] {Message:lj} {Properties:j}{NewLine}{Exception}"
    - Name: File
      Args:
        path: logs/service-.log
        rollingInterval: Day
        shared: true
        outputTemplate: "{Timestamp:yyyy-MM-dd HH:mm:ss.fff} [{Level:u3}] {SourceContext} {Message:lj} {Properties:j}{NewLine}{Exception}"
    - Name: File
      Args:
        path: logs/error-.log
        rollingInterval: Day
        shared: true
        restrictedToMinimumLevel: Error
        outputTemplate: "{Timestamp:yyyy-MM-dd HH:mm:ss.fff} [{Level:u3}] {SourceContext} {Message:lj} {Properties:j}{NewLine}{Exception}"
