version: '3.8'

# هذا الملف يقوم بدمج الخدمات من docker-compose.db.yml مع docker-compose.yml
# يتم تحميله تلقائيًا عند تنفيذ أمر docker-compose up

services:
  # تضمين خدمات قواعد البيانات من الملف الإضافي
  sqlserver:
    extends:
      file: docker-compose.db.yml
      service: sqlserver

  elasticsearch:
    extends:
      file: docker-compose.db.yml
      service: elasticsearch

  kibana:
    extends:
      file: docker-compose.db.yml
      service: kibana

  adminer:
    extends:
      file: docker-compose.db.yml
      service: adminer
